DROP TABLE IF EXISTS chats

CREATE TABLE chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id TEXT NOT NULL,
    chat_log TEXT NOT NULL
);
